version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pmip_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pmuser
      POSTGRES_PASSWORD: pmpassword
      POSTGRES_DB: pmpdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pmuser -d pmpdb']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: pmip_api
    restart: unless-stopped
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgresql://pmuser:pmpassword@postgres:5432/pmpdb
      PORT: 4000
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      ADMIN_SECRET: ${ADMIN_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres_data:
